export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILED = 'POST_ORDER_FAILED';
export const PROCESS_ORDER = 'PROCESS_ORDER';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const REQUEST_ORDERS = 'REQUEST_ORDERS';
export const REQUEST_ORDERS_INIT = 'REQUEST_ORDERS_INIT';
export const REQUEST_ORDERS_SUCCESS = 'REQUEST_ORDERS_SUCCESS';
export const REQUEST_ORDERS_FAILED = 'REQUEST_ORDERS_FAILED';

export const AUTH_INIT= 'AUTH_INIT';
export const AUTH_FAILURE= 'AUTH_FAILURE';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';